# 빌드 스테이지
FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle settings.gradle .
COPY src src

RUN chmod +x ./gradlew

ARG SPRING_PROFILES_ACTIVE=prod
ARG DATABASE_NAME
ARG MONGODB_URI
ARG OAUTH_CLIENT_ID
ARG OAUTH_SECRET_KEY
ARG UNIV_API_KEY
ARG KAKAO_REST_API_KEY
ARG JWT_SECRET
ARG OPENAI_API_URI
ARG OPENAI_API_KEY
ARG OPENAI_MODEL

RUN SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE} \
    DATABASE_NAME=${DATABASE_NAME} \
    MONGODB_URI=${MONGODB_URI} \
    OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID} \
    OAUTH_SECRET_KEY=${OAUTH_SECRET_KEY} \
    UNIV_API_KEY=${UNIV_API_KEY} \
    KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY} \
    JWT_SECRET=${JWT_SECRET} \
    OPENAI_API_URI=${OPENAI_API_URI} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    OPENAI_MODEL=${OPENAI_MODEL} \
    ./gradlew clean bootJar -x test --no-daemon

# 실행 스테이지
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ARG SPRING_PROFILES_ACTIVE=prod
ARG DATABASE_NAME
ARG MONGODB_URI
ARG OAUTH_CLIENT_ID
ARG OAUTH_SECRET_KEY
ARG UNIV_API_KEY
ARG KAKAO_REST_API_KEY
ARG JWT_SECRET
ARG OPENAI_API_URI
ARG OPENAI_API_KEY
ARG OPENAI_MODEL

ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV MONGODB_URI=${MONGODB_URI}
ENV OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
ENV OAUTH_SECRET_KEY=${OAUTH_SECRET_KEY}
ENV UNIV_API_KEY=${UNIV_API_KEY}
ENV KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
ENV JWT_SECRET=${JWT_SECRET}
ENV OPENAI_API_URI=${OPENAI_API_URI}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV OPENAI_MODEL=${OPENAI_MODEL}

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
