FROM openjdk:11-jre-slim
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

# ARG 선언
ARG SPRING_PROFILES_ACTIVE
ARG DATABASE_NAME
ARG MONGODB_URI
ARG OAUTH_CLIENT_ID
ARG OAUTH_SECRET_KEY
ARG UNIV_API_KEY
ARG KAKAO_REST_API_KEY
ARG JWT_SECRET

# ENV 설정
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV MONGODB_URI=${MONGODB_URI}
ENV OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
ENV OAUTH_SECRET_KEY=${OAUTH_SECRET_KEY}
ENV UNIV_API_KEY=${UNIV_API_KEY}
ENV KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
ENV JWT_SECRET=${JWT_SECRET}

ENTRYPOINT ["java", "-jar", "/app.jar"]